#!/bin/bash
# ZOHALPAY one-time server setup (Ubuntu 22.04/24.04). Run as root:
#   curl -fsSL https://raw.githubusercontent.com/asadiradmehdi/digital-platform-v4.2/master/deploy/install.sh | bash
# Safe to re-run. Leaves other projects on the host (e.g. Tiuz) untouched: it only adds its own
# containers, volumes, an nginx site (if nginx already owns ports 80/443) and a systemd timer.
set -euo pipefail
REPO=https://github.com/asadiradmehdi/digital-platform-v4.2.git
DIR=/opt/zohalpay
say() { printf '\n\033[1;33m== %s\033[0m\n' "$*"; }
[[ $EUID -eq 0 ]] || { echo "Run as root (sudo -i)."; exit 1; }

say "1/7 Packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
command -v git >/dev/null || apt-get install -y -qq git
command -v curl >/dev/null || apt-get install -y -qq curl
if ! command -v docker >/dev/null; then apt-get install -y -qq docker.io; fi
if ! docker compose version >/dev/null 2>&1; then apt-get install -y -qq docker-compose-v2 || apt-get install -y -qq docker-compose-plugin; fi
systemctl enable --now docker >/dev/null

say "2/7 Swap (the build needs ~3 GB of memory)"
if [[ $(swapon --show | wc -l) -eq 0 ]]; then
  fallocate -l 2G /swapfile && chmod 600 /swapfile && mkswap /swapfile >/dev/null && swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

say "3/7 Code"
if [[ -d $DIR/.git ]]; then git -C "$DIR" fetch -q origin master && git -C "$DIR" reset -q --hard origin/master
else git clone -q --branch master "$REPO" "$DIR"; fi

say "4/7 Secrets (generated here, never leave this server)"
ENV=$DIR/deploy/.env
IP=$(curl -fsS4 https://api.ipify.org || hostname -I | awk '{print $1}')
HOST="$(echo "$IP" | tr . -).sslip.io"
if [[ ! -f $ENV ]]; then
  umask 077
  cat > "$ENV" <<CONF
# Generated by install.sh on $(date -Is). Keep private; back it up somewhere safe.
SITE_HOST=$HOST
NEXT_PUBLIC_SITE_URL=https://$HOST
APP_PORT=3100
TRUST_PROXY=true
POSTGRES_PASSWORD=$(openssl rand -hex 24)
APP_DB_PASSWORD=$(openssl rand -hex 24)
SECRETS_MASTER_KEY=$(openssl rand -hex 32)
INTERNAL_API_SECRET=$(openssl rand -hex 32)
STORAGE_SECRET=$(openssl rand -hex 32)
QUEUE_CRON_SECRET=$(openssl rand -hex 32)
PRICING_CRON_SECRET=$(openssl rand -hex 32)
SUPPORT_HOURS="شنبه تا پنج‌شنبه، ۹ صبح تا ۹ شب"
SUPPORT_PHONES=
CONF
fi
set -a; . "$ENV"; set +a
mkdir -p "$DIR/deploy/backups"

say "5/7 HTTPS front door for $SITE_HOST"
busy() { ss -ltnH "( sport = :$1 )" | grep -q .; }
if ! busy 80 && ! busy 443; then
  sed -i '/^PROXY=/d' "$ENV"; echo "PROXY=caddy" >> "$ENV"
  command -v ufw >/dev/null && ufw status | grep -q active && ufw allow 80,443/tcp >/dev/null || true
  echo "Ports 80/443 are free: ZOHALPAY's own Caddy will serve HTTPS."
elif systemctl is-active --quiet nginx; then
  sed -i '/^PROXY=/d' "$ENV"; echo "PROXY=nginx" >> "$ENV"
  echo "nginx already serves this host (Tiuz?). Adding a separate site for $SITE_HOST only."
  apt-get install -y -qq certbot python3-certbot-nginx >/dev/null
  cat > /etc/nginx/sites-available/zohalpay <<NGX
server {
  listen 80;
  server_name $SITE_HOST;
  client_max_body_size 2m;
  location /api/internal/ { return 404; }
  location / {
    proxy_pass http://127.0.0.1:${APP_PORT};
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$remote_addr;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-Host \$host;
  }
}
NGX
  ln -sf /etc/nginx/sites-available/zohalpay /etc/nginx/sites-enabled/zohalpay
  nginx -t && systemctl reload nginx
  certbot --nginx -d "$SITE_HOST" --non-interactive --agree-tos --register-unsafely-without-email --redirect || echo "certbot failed; send the output above to Claude."
else
  echo "Ports 80/443 are used by something other than nginx:"; ss -ltnp '( sport = :80 or sport = :443 )' || true
  docker ps --format '{{.Names}}\t{{.Ports}}' || true
  echo "ZOHALPAY will still start on 127.0.0.1:${APP_PORT}. Send this output to Claude to finish HTTPS."
  sed -i '/^PROXY=/d' "$ENV"; echo "PROXY=none" >> "$ENV"
fi

say "6/7 Build and start (first build takes a few minutes)"
cd "$DIR/deploy"
PROFILE=$(grep -q '^PROXY=caddy' .env && echo "--profile caddy" || true)
docker compose $PROFILE up -d --build

say "7/7 Auto-update from GitHub every 2 minutes"
cat > /etc/systemd/system/zohalpay-update.service <<UNIT
[Unit]
Description=ZOHALPAY: deploy new commits from master
After=docker.service network-online.target
[Service]
Type=oneshot
ExecStart=$DIR/deploy/update.sh
UNIT
cat > /etc/systemd/system/zohalpay-update.timer <<UNIT
[Unit]
Description=ZOHALPAY: check GitHub for new commits
[Timer]
OnBootSec=2min
OnUnitActiveSec=2min
[Install]
WantedBy=timers.target
UNIT
systemctl daemon-reload && systemctl enable --now zohalpay-update.timer >/dev/null

for i in $(seq 1 60); do curl -fsS "http://127.0.0.1:${APP_PORT}/api/v1/health" >/dev/null 2>&1 && break; sleep 3; done
if curl -fsS "http://127.0.0.1:${APP_PORT}/api/v1/health" >/dev/null 2>&1; then
  say "Done. ZOHALPAY is live at: https://$SITE_HOST"
else
  say "The app did not answer yet. Send the output of: cd $DIR/deploy && docker compose logs --tail 80 app migrate"
fi
