import { NextRequest, NextResponse } from 'next/server';
import { randomUUID } from 'node:crypto';
import { withTenantTransaction } from '../../../../../server/core/db';
import { hashPassword } from '../../../../../server/identity/password';
import { createSession } from '../../../../../server/identity/sessions';
import { correlationId, handleRouteError, json } from '../../../../../server/core/http';
import { requireString } from '../../../../../server/core/validation';
import { AppError } from '../../../../../server/core/errors';
import { consumeDistributedRateLimit } from '../../../../../server/core/distributed-rate-limit';
import { assertSameOrigin, clientFingerprint } from '../../../../../server/core/security-boundary';
import { recordSecurityEvent } from '../../../../../server/core/security-events';
import { setSessionCookie } from '../../../../../server/identity/session-cookie';
import { assertStrongPassword } from '../../../../../server/identity/password-policy';
import { attachReferralAtSignup, REFERRAL_COOKIE, referralCodeFromCookies } from '../../../../../server/referrals/service';
export async function POST(request:NextRequest){const id=correlationId(request);try{assertSameOrigin(request);const ip=clientFingerprint(request);await consumeDistributedRateLimit({key:`register:${ip}`,scope:'auth.register.ip',windowSeconds:60,maxRequests:5});const isJson=request.headers.get('content-type')?.includes('application/json') ?? false;const body:Record<string,unknown>=isJson?await request.json() as Record<string,unknown>:Object.fromEntries((await request.formData()).entries());const email=requireString(body.email,'email',5,320).toLowerCase();const password=requireString(body.password,'password',14,200);assertStrongPassword(password);const name=requireString(body.name,'name',2,120);if(!/^\S+@\S+\.\S+$/.test(email))throw new AppError('VALIDATION_ERROR','Email is invalid.');const referralCode=typeof body.referralCode==='string'&&body.referralCode.trim()?body.referralCode:referralCodeFromCookies(request.headers.get('cookie'));const passwordHash=await hashPassword(password);// Ids are minted up front so the whole signup runs in the new workspace's RLS context (wallets are tenant-protected).
const userId=randomUUID();const workspaceId=randomUUID();const result=await withTenantTransaction(workspaceId,userId,async client=>{const existing=await client.query(`SELECT id FROM users WHERE lower(email)=lower($1)`,[email]);if(existing.rows[0])throw new AppError('CONFLICT','An account with this email already exists.');const user=(await client.query<{id:string}>(`INSERT INTO users(id,email,display_name) VALUES($1,$2,$3) RETURNING id`,[userId,email,name])).rows[0];const workspace=(await client.query<{id:string;slug:string}>(`INSERT INTO workspaces(id,owner_user_id,name,slug) VALUES($1,$2,$3,$4) RETURNING id,slug`,[workspaceId,user.id,`${name} Workspace`,`ws-${user.id.slice(0,8)}`])).rows[0];const member=(await client.query<{id:string}>(`INSERT INTO workspace_members(workspace_id,user_id,joined_at) VALUES($1,$2,now()) RETURNING id`,[workspace.id,user.id])).rows[0];const role=(await client.query<{id:string}>(`INSERT INTO roles(workspace_id,name,is_system) VALUES($1,'Owner',true) RETURNING id`,[workspace.id])).rows[0];await client.query(`INSERT INTO member_roles(member_id,role_id) VALUES($1,$2)`,[member.id,role.id]);await client.query(`INSERT INTO role_permissions(role_id,permission_id) SELECT $1,id FROM permissions WHERE key <> 'admin.ops'`,[role.id]);await client.query(`INSERT INTO user_credentials(user_id,credential_type,credential_hash) VALUES($1,'password',$2)`,[user.id,passwordHash]);const wallet=(await client.query<{id:string}>(`INSERT INTO wallets(workspace_id,currency) VALUES($1,'IRR') RETURNING id`,[workspace.id])).rows[0];await client.query(`INSERT INTO ledger_accounts(wallet_id,account_code) VALUES($1,'MAIN'),($1,'AVAILABLE'),($1,'HELD'),($1,'REFUNDS')`,[wallet.id]);await attachReferralAtSignup(client,{code:referralCode,userId:user.id,workspaceId:workspace.id,ip});return {userId:user.id,workspaceId:workspace.id};});await recordSecurityEvent({eventType:'ACCOUNT_REGISTERED',severity:'INFO',userId:result.userId,workspaceId:result.workspaceId,sourceIp:ip,userAgent:request.headers.get('user-agent')??undefined,correlationId:id});const token=await createSession(result.userId);const response=isJson?json({ok:true},{correlationId:id,status:201}):NextResponse.redirect(new URL('/dashboard',request.url));response.headers.set('x-correlation-id',id);setSessionCookie(response, token);if(referralCode)response.cookies.delete(REFERRAL_COOKIE);return response;}catch(e){return handleRouteError(e,id);}}
