import { NextRequest, NextResponse } from 'next/server';
import { randomUUID } from 'node:crypto';
import { withTenantTransaction } from '../../../../../server/core/db';
import { hashPassword } from '../../../../../server/identity/password';
import { createSession } from '../../../../../server/identity/sessions';
import { correlationId, handleRouteError, json } from '../../../../../server/core/http';
import { requireString } from '../../../../../server/core/validation';
import { AppError } from '../../../../../server/core/errors';
import { consumeDistributedRateLimit } from '../../../../../server/core/distributed-rate-limit';
import { assertSameOrigin, clientFingerprint } from '../../../../../server/core/security-boundary';
import { recordSecurityEvent } from '../../../../../server/core/security-events';
import { setSessionCookie } from '../../../../../server/identity/session-cookie';
import { assertStrongPassword } from '../../../../../server/identity/password-policy';
import { REFERRAL_COOKIE, referralCodeFromCookies } from '../../../../../server/referrals/service';
import { createPersonalWorkspace } from '../../../../../server/identity/signup';
import { safeNextPath } from '../../../../../server/identity/sign-in';
/** Field checks answer in Persian: the message is shown to the customer as-is. */
function persianField<T>(read:()=>T,message:string):T{try{return read();}catch{throw new AppError('VALIDATION_ERROR',message);}}
export async function POST(request:NextRequest){const id=correlationId(request);try{assertSameOrigin(request);const ip=clientFingerprint(request);await consumeDistributedRateLimit({key:`register:${ip}`,scope:'auth.register.ip',windowSeconds:60,maxRequests:5});const isJson=request.headers.get('content-type')?.includes('application/json') ?? false;const body:Record<string,unknown>=isJson?await request.json() as Record<string,unknown>:Object.fromEntries((await request.formData()).entries());const email=persianField(()=>requireString(body.email,'email',5,320),'آدرس ایمیل درست نیست.').toLowerCase();const password=persianField(()=>requireString(body.password,'password',14,200),'رمز عبور باید بین ۱۴ تا ۲۰۰ کاراکتر باشد.');assertStrongPassword(password,{email:String(body.email??'')});const name=persianField(()=>requireString(body.name,'name',2,120),'نام و نام خانوادگی را کامل وارد کنید.');if(!/^\S+@\S+\.\S+$/.test(email))throw new AppError('VALIDATION_ERROR','آدرس ایمیل درست نیست.');const referralCode=typeof body.referralCode==='string'&&body.referralCode.trim()?body.referralCode:referralCodeFromCookies(request.headers.get('cookie'));const passwordHash=await hashPassword(password);// Ids are minted up front so the whole signup runs in the new workspace's RLS context (wallets are tenant-protected).
const userId=randomUUID();const workspaceId=randomUUID();const result=await withTenantTransaction(workspaceId,userId,async client=>{const existing=await client.query(`SELECT id FROM users WHERE lower(email)=lower($1)`,[email]);if(existing.rows[0])throw new AppError('CONFLICT','با این ایمیل قبلاً حساب ساخته شده است. وارد شوید.');const user=(await client.query<{id:string}>(`INSERT INTO users(id,email,display_name) VALUES($1,$2,$3) RETURNING id`,[userId,email,name])).rows[0];await client.query(`INSERT INTO user_credentials(user_id,credential_type,credential_hash) VALUES($1,'password',$2)`,[user.id,passwordHash]);// Workspace, Owner role (staff-only keys excluded), wallet + ledger accounts and invite attribution: one shared rule for every signup path.
await createPersonalWorkspace(client,{userId:user.id,workspaceId,name,referralCode,ip});return {userId:user.id,workspaceId};});await recordSecurityEvent({eventType:'ACCOUNT_REGISTERED',severity:'INFO',userId:result.userId,workspaceId:result.workspaceId,sourceIp:ip,userAgent:request.headers.get('user-agent')??undefined,correlationId:id});const token=await createSession(result.userId,undefined,{authMethod:'PASSWORD',lastUserAgent:request.headers.get('user-agent')??undefined});const next=safeNextPath(body.next);const response=isJson?json({ok:true,next},{correlationId:id,status:201}):NextResponse.redirect(new URL(next,request.url));response.headers.set('x-correlation-id',id);setSessionCookie(response, token);if(referralCode)response.cookies.delete(REFERRAL_COOKIE);return response;}catch(e){return handleRouteError(e,id);}}
