import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import type { PropsWithChildren, ReactNode } from 'react';
import { theme } from '../theme';
export function Title({ eyebrow, children, description }: { eyebrow?: string; children: ReactNode; description?: string }) { return <View style={styles.heading}>{eyebrow?<Text style={styles.eyebrow}>{eyebrow}</Text>:null}<Text style={styles.title}>{children}</Text>{description?<Text style={styles.muted}>{description}</Text>:null}</View>; }
export function Card({ children, emphasis=false, compact=false }: PropsWithChildren<{emphasis?:boolean;compact?:boolean}>) { return <View style={[styles.card,emphasis&&styles.cardEmphasis,compact&&styles.cardCompact]}>{children}</View>; }
export function Action({ children,onPress,tone='primary',disabled=false }: {children:ReactNode;onPress?:()=>void;tone?:'primary'|'secondary'|'danger'|'ghost';disabled?:boolean}) { const dark=tone==='primary'||tone==='danger'; return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({pressed})=>[styles.button,tone==='primary'?styles.primary:tone==='danger'?styles.danger:tone==='ghost'?styles.ghost:styles.secondary,pressed&&styles.pressed]}><Text style={dark?styles.buttonDark:styles.buttonLight}>{children}</Text></Pressable>; }
export function Metric({label,value,hint,accent=false}: {label:string;value:string;hint?:string;accent?:boolean}) { return <Card emphasis={accent}><View style={styles.metricTop}><Text style={styles.muted}>{label}</Text><View style={[styles.metricDot,accent&&styles.metricDotAccent]}/></View><Text style={[styles.metric,accent&&styles.metricAccent]}>{value}</Text>{hint?<Text style={styles.hint}>{hint}</Text>:null}</Card>; }
export function UsageBar({value}:{value:number}) { const pct=Math.max(0,Math.min(100,value)); return <View style={styles.usageTrack}><View style={[styles.usageFill,{width:`${pct}%`}]}/></View>; }
export function Status({children,tone='neutral'}:{children:ReactNode;tone?:'success'|'info'|'warning'|'danger'|'neutral'}) { return <View style={[styles.status,styles[`status_${tone}`]]}><Text style={styles.statusText}>{children}</Text></View>; }
export function Section({title,action}:{title:string;action?:ReactNode}) { return <View style={styles.sectionRow}><Text style={styles.section}>{title}</Text>{action}</View>; }
export function State({loading=false,error,empty}:{loading?:boolean;error?:string;empty?:string}) { if(loading)return <Card><View style={styles.center}><ActivityIndicator color={theme.colors.accentStrong}/><Text style={styles.muted}>در حال دریافت اطلاعات...</Text></View></Card>; if(error)return <Card><Text style={styles.error}>{error}</Text></Card>; if(empty)return <Card><Text style={styles.muted}>{empty}</Text></Card>; return null; }
export function Divider(){return <View style={styles.divider}/>}
const styles=StyleSheet.create({heading:{gap:7,paddingTop:4},eyebrow:{color:theme.colors.accentStrong,fontSize:9,fontWeight:'800',letterSpacing:1.5},title:{color:theme.colors.ink,fontSize:30,fontWeight:'800',letterSpacing:-.7},muted:{color:theme.colors.muted,fontSize:12,lineHeight:21},card:{backgroundColor:theme.colors.surface,borderColor:theme.colors.line,borderWidth:1,borderRadius:theme.radius.lg,padding:theme.spacing.lg,gap:10,shadowColor:'#000',shadowOpacity:.22,shadowRadius:22,shadowOffset:{width:0,height:12},elevation:4},cardEmphasis:{backgroundColor:theme.colors.bgElevated,borderColor:theme.colors.lineStrong},cardCompact:{padding:14},metricTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},metricDot:{width:7,height:7,borderRadius:4,backgroundColor:theme.colors.lineStrong},metricDotAccent:{backgroundColor:theme.colors.accent},metric:{color:theme.colors.ink,fontSize:24,fontWeight:'800',letterSpacing:-.6},metricAccent:{color:theme.colors.accentStrong},hint:{color:theme.colors.subtle,fontSize:10,lineHeight:18},usageTrack:{height:7,borderRadius:99,backgroundColor:theme.colors.surface3,overflow:'hidden'},usageFill:{height:'100%',borderRadius:99,backgroundColor:theme.colors.accent},status:{alignSelf:'flex-start',paddingHorizontal:8,paddingVertical:4,borderRadius:99},status_success:{backgroundColor:'rgba(22,163,74,.08)'},status_info:{backgroundColor:'rgba(2,132,199,.08)'},status_warning:{backgroundColor:'rgba(217,119,6,.08)'},status_danger:{backgroundColor:'rgba(220,38,38,.08)'},status_neutral:{backgroundColor:theme.colors.surface3},statusText:{color:theme.colors.ink,fontSize:9,fontWeight:'700'},button:{minHeight:46,borderRadius:theme.radius.md,alignItems:'center',justifyContent:'center',paddingHorizontal:16},primary:{backgroundColor:theme.colors.accent},secondary:{backgroundColor:theme.colors.surface2,borderWidth:1,borderColor:theme.colors.line},danger:{backgroundColor:theme.colors.danger},ghost:{backgroundColor:'transparent'},buttonDark:{color:'#fff',fontWeight:'800'},buttonLight:{color:theme.colors.ink,fontWeight:'700'},pressed:{opacity:.82},error:{color:theme.colors.danger,fontSize:13},center:{alignItems:'center',gap:8},sectionRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},section:{color:theme.colors.ink,fontSize:16,fontWeight:'800'},divider:{height:1,backgroundColor:theme.colors.line}});
